jobs:
  build_shrp:
    machine: true
    image: ubuntu-2004:current
    working_directory: ~/shrp
    environment:
      DEVICE: kirin710
      ANDROID_ROOT: ~/shrp
    steps:
      - checkout
      - run:
          name: Initialization environment
          command: |
            sudo apt update
            sudo apt-get install -y \
            git gnupg flex ccache bison gperf build-essential \
            zip bzr curl libc6-dev x11proto-core-dev \
            libgl1-mesa-dev g++-multilib tofrodos \
            python3-markdown libxml2-utils xsltproc schedtool \
            liblz4-tool bc lzop imagemagick libncurses5 rsync \
            python-is-python3

      - run:
          name: Download repo
          command: |
            mkdir -p ~/bin
            wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P ~/bin
            chmod +x ~/bin/repo
            sed -i '1s/^#!\/usr\/bin\/env python/#!\/usr\/bin\/env python3/' ~/bin/repo
            git config --global user.name "aymanrgab"
            git config --global user.email "aymanrar2c@gmail.com"
            
      - run:
          name: Downloading source code
          command: |
            mkdir -p $ANDROID_ROOT
            cd $ANDROID_ROOT
            repo init -u https://github.com/SHRP/manifest.git -b v3_9.0
            repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
            git clone https://github.com/Exynos7880-Linux/android_device_huawei_kirin710-shrp.git device/huawei/kirin710

      - run:
          name: Build Recovery
          command: |
            cd $ANDROID_ROOT
            export ALLOW_MISSING_DEPENDENCIES=true; source build/envsetup.sh; lunch omni_kirin710-eng; mka recoveryimage
            tar -czf ~/kirin710_shrp.tar.gz /home/circleci/shrp/~/shrp/out/target/product/kirin710/SHRP_*.zip
      - run:
          name: Check free disk
          when: on_fail
          command: |
            df -h

      - store_artifacts:
          path: ~/kirin710_shrp.tar.gz

          
workflows:
  version: 2
  build_and_upload:
    jobs:
      - build_shrp
